site_name: StudyLion Bot - Tutorials
site_url: http://docs.lionbot.org/

repo_url: https://github.com/StudyLions/StudyLion
repo_name: StudyLions/StudyLion

theme:
  name: material
  logo: assets/lion-love-emote.png
  favicon: assets/lion-love-emote.png
  features:
    - navigation.instant
    - navigation.top
    - toc.integrate
  palette:
    accent: black

nav:
  - Home: 'index.md'
  - Configuring StudyLion as a server owner: "as-a-server-owner.md"
  - Using StudyLion as a member: "as-a-member.md"

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/mrdbourke
    - icon: fontawesome/brands/github
      link: https://github.com/StudyLions
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCr8O8l5cCX85Oem1d18EezQ