# ============================================================
# AI-GENERATED FILE
# Created: 2026-03-13
# Purpose: Generate translations for medium domains:
#          config, stats-gui, monthly-gui, lion-core,
#          text-tracker, sysadmin, settings_base, meta
# ============================================================

import os, sys, json
sys.path.insert(0, os.path.dirname(__file__))
from po_utils import parse_pot, write_po_files, load_existing_translations, TEMPLATES_DIR, TARGET_LOCALES

def load_salvaged(domain):
    json_path = os.path.join(os.path.dirname(__file__), 'salvaged_translations.json')
    if not os.path.exists(json_path): return {}
    with open(json_path, 'r', encoding='utf-8') as f: all_s = json.load(f)
    if domain not in all_s: return {}
    result = {}
    for key_str, locale_map in all_s[domain].items():
        parts = key_str.split('|||', 1)
        ctx = parts[0] if parts[0] else None
        result[(ctx, parts[1])] = locale_map
    return result

L = TARGET_LOCALES

# Helper: hours translations reusable across domains
H = {"bg":"часа","cs":"hodin","da":"timer","de":"Stunden","el":"ώρες","es_ES":"horas","fi":"tuntia","fr":"heures","hi":"घंटे","hr":"sati","hu":"óra","id":"jam","it":"ore","ja":"時間","ko":"시간","lt":"val.","nl":"uur","no":"timer","pl":"godzin","pt_BR":"horas","ro":"ore","ru":"часов","sv_SE":"timmar","th":"ชั่วโมง","tr":"saat","uk":"годин","vi":"giờ","zh_CN":"小时","zh_TW":"小時","he_IL":"שעות"}
# Weekday abbreviations (Sunday-first for stats-gui, Monday-first for monthly-gui)
WD_SUN = {"bg":"Н,П,В,С,Ч,П,С","cs":"N,P,Ú,S,Č,P,S","da":"S,M,T,O,T,F,L","de":"S,M,D,M,D,F,S","el":"Κ,Δ,Τ,Τ,Π,Π,Σ","es_ES":"D,L,M,X,J,V,S","fi":"S,M,T,K,T,P,L","fr":"D,L,M,M,J,V,S","hi":"र,सो,मं,बु,गु,शु,श","hr":"N,P,U,S,Č,P,S","hu":"V,H,K,Sz,Cs,P,Sz","id":"M,S,S,R,K,J,S","it":"D,L,M,M,G,V,S","ja":"日,月,火,水,木,金,土","ko":"일,월,화,수,목,금,토","lt":"S,P,A,T,K,P,Š","nl":"Z,M,D,W,D,V,Z","no":"S,M,T,O,T,F,L","pl":"N,P,W,Ś,C,P,S","pt_BR":"D,S,T,Q,Q,S,S","ro":"D,L,M,M,J,V,S","ru":"В,П,В,С,Ч,П,С","sv_SE":"S,M,T,O,T,F,L","th":"อ,จ,อ,พ,พ,ศ,ส","tr":"P,P,S,Ç,P,C,C","uk":"Н,П,В,С,Ч,П,С","vi":"CN,T2,T3,T4,T5,T6,T7","zh_CN":"日,一,二,三,四,五,六","zh_TW":"日,一,二,三,四,五,六","he_IL":"א,ב,ג,ד,ה,ו,ש"}
WD_MON = {"bg":"П,В,С,Ч,П,С,Н","cs":"P,Ú,S,Č,P,S,N","da":"M,T,O,T,F,L,S","de":"M,D,M,D,F,S,S","el":"Δ,Τ,Τ,Π,Π,Σ,Κ","es_ES":"L,M,X,J,V,S,D","fi":"M,T,K,T,P,L,S","fr":"L,M,M,J,V,S,D","hi":"सो,मं,बु,गु,शु,श,र","hr":"P,U,S,Č,P,S,N","hu":"H,K,Sz,Cs,P,Sz,V","id":"S,S,R,K,J,S,M","it":"L,M,M,G,V,S,D","ja":"月,火,水,木,金,土,日","ko":"월,화,수,목,금,토,일","lt":"P,A,T,K,P,Š,S","nl":"M,D,W,D,V,Z,Z","no":"M,T,O,T,F,L,S","pl":"P,W,Ś,C,P,S,N","pt_BR":"S,T,Q,Q,S,S,D","ro":"L,M,M,J,V,S,D","ru":"П,В,С,Ч,П,С,В","sv_SE":"M,T,O,T,F,L,S","th":"จ,อ,พ,พ,ศ,ส,อ","tr":"P,S,Ç,P,C,C,P","uk":"П,В,С,Ч,П,С,Н","vi":"T2,T3,T4,T5,T6,T7,CN","zh_CN":"一,二,三,四,五,六,日","zh_TW":"一,二,三,四,五,六,日","he_IL":"ב,ג,ד,ה,ו,ש,א"}
MONTHS = {
    "bg":"ЯНУАРИ,ФЕВРУАРИ,МАРТ,АПРИЛ,МАЙ,ЮНИ,ЮЛИ,АВГУСТ,СЕПТЕМВРИ,ОКТОМВРИ,НОЕМВРИ,ДЕКЕМВРИ",
    "cs":"LEDEN,ÚNOR,BŘEZEN,DUBEN,KVĚTEN,ČERVEN,ČERVENEC,SRPEN,ZÁŘÍ,ŘÍJEN,LISTOPAD,PROSINEC",
    "da":"JANUAR,FEBRUAR,MARTS,APRIL,MAJ,JUNI,JULI,AUGUST,SEPTEMBER,OKTOBER,NOVEMBER,DECEMBER",
    "de":"JANUAR,FEBRUAR,MÄRZ,APRIL,MAI,JUNI,JULI,AUGUST,SEPTEMBER,OKTOBER,NOVEMBER,DEZEMBER",
    "el":"ΙΑΝΟΥΑΡΙΟΣ,ΦΕΒΡΟΥΑΡΙΟΣ,ΜΑΡΤΙΟΣ,ΑΠΡΙΛΙΟΣ,ΜΑΪΟΣ,ΙΟΥΝΙΟΣ,ΙΟΥΛΙΟΣ,ΑΥΓΟΥΣΤΟΣ,ΣΕΠΤΕΜΒΡΙΟΣ,ΟΚΤΩΒΡΙΟΣ,ΝΟΕΜΒΡΙΟΣ,ΔΕΚΕΜΒΡΙΟΣ",
    "es_ES":"ENERO,FEBRERO,MARZO,ABRIL,MAYO,JUNIO,JULIO,AGOSTO,SEPTIEMBRE,OCTUBRE,NOVIEMBRE,DICIEMBRE",
    "fi":"TAMMIKUU,HELMIKUU,MAALISKUU,HUHTIKUU,TOUKOKUU,KESÄKUU,HEINÄKUU,ELOKUU,SYYSKUU,LOKAKUU,MARRASKUU,JOULUKUU",
    "fr":"JANVIER,FÉVRIER,MARS,AVRIL,MAI,JUIN,JUILLET,AOÛT,SEPTEMBRE,OCTOBRE,NOVEMBRE,DÉCEMBRE",
    "hi":"जनवरी,फरवरी,मार्च,अप्रैल,मई,जून,जुलाई,अगस्त,सितंबर,अक्टूबर,नवंबर,दिसंबर",
    "hr":"SIJEČANJ,VELJAČA,OŽUJAK,TRAVANJ,SVIBANJ,LIPANJ,SRPANJ,KOLOVOZ,RUJAN,LISTOPAD,STUDENI,PROSINAC",
    "hu":"JANUÁR,FEBRUÁR,MÁRCIUS,ÁPRILIS,MÁJUS,JÚNIUS,JÚLIUS,AUGUSZTUS,SZEPTEMBER,OKTÓBER,NOVEMBER,DECEMBER",
    "id":"JANUARI,FEBRUARI,MARET,APRIL,MEI,JUNI,JULI,AGUSTUS,SEPTEMBER,OKTOBER,NOVEMBER,DESEMBER",
    "it":"GENNAIO,FEBBRAIO,MARZO,APRILE,MAGGIO,GIUGNO,LUGLIO,AGOSTO,SETTEMBRE,OTTOBRE,NOVEMBRE,DICEMBRE",
    "ja":"1月,2月,3月,4月,5月,6月,7月,8月,9月,10月,11月,12月",
    "ko":"1월,2월,3월,4월,5월,6월,7월,8월,9월,10월,11월,12월",
    "lt":"SAUSIS,VASARIS,KOVAS,BALANDIS,GEGUŽĖ,BIRŽELIS,LIEPA,RUGPJŪTIS,RUGSĖJIS,SPALIS,LAPKRITIS,GRUODIS",
    "nl":"JANUARI,FEBRUARI,MAART,APRIL,MEI,JUNI,JULI,AUGUSTUS,SEPTEMBER,OKTOBER,NOVEMBER,DECEMBER",
    "no":"JANUAR,FEBRUAR,MARS,APRIL,MAI,JUNI,JULI,AUGUST,SEPTEMBER,OKTOBER,NOVEMBER,DESEMBER",
    "pl":"STYCZEŃ,LUTY,MARZEC,KWIECIEŃ,MAJ,CZERWIEC,LIPIEC,SIERPIEŃ,WRZESIEŃ,PAŹDZIERNIK,LISTOPAD,GRUDZIEŃ",
    "pt_BR":"JANEIRO,FEVEREIRO,MARÇO,ABRIL,MAIO,JUNHO,JULHO,AGOSTO,SETEMBRO,OUTUBRO,NOVEMBRO,DEZEMBRO",
    "ro":"IANUARIE,FEBRUARIE,MARTIE,APRILIE,MAI,IUNIE,IULIE,AUGUST,SEPTEMBRIE,OCTOMBRIE,NOIEMBRIE,DECEMBRIE",
    "ru":"ЯНВАРЬ,ФЕВРАЛЬ,МАРТ,АПРЕЛЬ,МАЙ,ИЮНЬ,ИЮЛЬ,АВГУСТ,СЕНТЯБРЬ,ОКТЯБРЬ,НОЯБРЬ,ДЕКАБРЬ",
    "sv_SE":"JANUARI,FEBRUARI,MARS,APRIL,MAJ,JUNI,JULI,AUGUSTI,SEPTEMBER,OKTOBER,NOVEMBER,DECEMBER",
    "th":"มกราคม,กุมภาพันธ์,มีนาคม,เมษายน,พฤษภาคม,มิถุนายน,กรกฎาคม,สิงหาคม,กันยายน,ตุลาคม,พฤศจิกายน,ธันวาคม",
    "tr":"OCAK,ŞUBAT,MART,NİSAN,MAYIS,HAZİRAN,TEMMUZ,AĞUSTOS,EYLÜL,EKİM,KASIM,ARALIK",
    "uk":"СІЧЕНЬ,ЛЮТИЙ,БЕРЕЗЕНЬ,КВІТЕНЬ,ТРАВЕНЬ,ЧЕРВЕНЬ,ЛИПЕНЬ,СЕРПЕНЬ,ВЕРЕСЕНЬ,ЖОВТЕНЬ,ЛИСТОПАД,ГРУДЕНЬ",
    "vi":"THÁNG 1,THÁNG 2,THÁNG 3,THÁNG 4,THÁNG 5,THÁNG 6,THÁNG 7,THÁNG 8,THÁNG 9,THÁNG 10,THÁNG 11,THÁNG 12",
    "zh_CN":"一月,二月,三月,四月,五月,六月,七月,八月,九月,十月,十一月,十二月",
    "zh_TW":"一月,二月,三月,四月,五月,六月,七月,八月,九月,十月,十一月,十二月",
    "he_IL":"ינואר,פברואר,מרץ,אפריל,מאי,יוני,יולי,אוגוסט,ספטמבר,אוקטובר,נובמבר,דצמבר",
}

STATS_GUI = {
    ("skin:stats|header:col1", "STATISTICS"): {
        "bg":"СТАТИСТИКА","cs":"STATISTIKY","da":"STATISTIK","de":"STATISTIKEN","el":"ΣΤΑΤΙΣΤΙΚΑ","es_ES":"ESTADÍSTICAS","fi":"TILASTOT","fr":"STATISTIQUES","hi":"आँकड़े","hr":"STATISTIKA","hu":"STATISZTIKÁK","id":"STATISTIK","it":"STATISTICHE","ja":"統計","ko":"통계","lt":"STATISTIKA","nl":"STATISTIEKEN","no":"STATISTIKK","pl":"STATYSTYKI","pt_BR":"ESTATÍSTICAS","ro":"STATISTICI","ru":"СТАТИСТИКА","sv_SE":"STATISTIK","th":"สถิติ","tr":"İSTATİSTİKLER","uk":"СТАТИСТИКА","vi":"THỐNG KÊ","zh_CN":"统计","zh_TW":"統計","he_IL":"סטטיסטיקה",
    },
    ("skin:stats|subheader:leaderboard", "LEADERBOARD POSITION"): {
        "bg":"ПОЗИЦИЯ В КЛАСАЦИЯТА","cs":"POZICE V ŽEBŘÍČKU","da":"RANGLISTEPOSITION","de":"RANGLISTENPOSITION","el":"ΘΕΣΗ ΚΑΤΆΤΑΞΗΣ","es_ES":"POSICIÓN EN LA TABLA","fi":"SIJOITUS","fr":"POSITION AU CLASSEMENT","hi":"लीडरबोर्ड स्थिति","hr":"POZICIJA NA LJESTVICI","hu":"RANGLISTA POZÍCIÓ","id":"POSISI PERINGKAT","it":"POSIZIONE IN CLASSIFICA","ja":"ランキング順位","ko":"리더보드 순위","lt":"POZICIJA LENTELĖJE","nl":"RANGLIJSTPOSITIE","no":"RANGLISTEPOSISJON","pl":"POZYCJA W RANKINGU","pt_BR":"POSIÇÃO NO RANKING","ro":"POZIȚIE ÎN CLASAMENT","ru":"ПОЗИЦИЯ В РЕЙТИНГЕ","sv_SE":"TOPPLISTEPOSITION","th":"ตำแหน่งในกระดานผู้นำ","tr":"SIRALAMA KONUMU","uk":"ПОЗИЦІЯ В РЕЙТИНГУ","vi":"VỊ TRÍ BẢNG XẾP HẠNG","zh_CN":"排行榜排名","zh_TW":"排行榜排名","he_IL":"מיקום בטבלה",
    },
    ("skin:stats|mode:study|subheader:study", "STUDY TIME"): {
        "bg":"УЧЕБНО ВРЕМЕ","cs":"DOBA STUDIA","da":"STUDIETID","de":"LERNZEIT","el":"ΧΡΟΝΟΣ ΜΕΛΕΤΗΣ","es_ES":"TIEMPO DE ESTUDIO","fi":"OPISKELUAIKA","fr":"TEMPS D'ÉTUDE","hi":"अध्ययन का समय","hr":"VRIJEME UČENJA","hu":"TANULÁSI IDŐ","id":"WAKTU BELAJAR","it":"TEMPO DI STUDIO","ja":"学習時間","ko":"학습 시간","lt":"MOKYMOSI LAIKAS","nl":"STUDIETIJD","no":"STUDIETID","pl":"CZAS NAUKI","pt_BR":"TEMPO DE ESTUDO","ro":"TIMP DE STUDIU","ru":"ВРЕМЯ УЧЁБЫ","sv_SE":"STUDIETID","th":"เวลาเรียน","tr":"ÇALIŞMA SÜRESİ","uk":"ЧАС НАВЧАННЯ","vi":"THỜI GIAN HỌC","zh_CN":"学习时间","zh_TW":"學習時間","he_IL":"זמן לימוד",
    },
    ("skin:stats|mode:voice|subheader:study", "VOICE TIME"): {
        "bg":"ВРЕМЕ В ГЛАСОВ КАНАЛ","cs":"ČAS V HLASOVÉM KANÁLU","da":"TALETID","de":"SPRACHZEIT","el":"ΧΡΟΝΟΣ ΦΩΝΗΣ","es_ES":"TIEMPO DE VOZ","fi":"ÄÄNIAIKA","fr":"TEMPS VOCAL","hi":"वॉइस समय","hr":"VRIJEME U GLASOVNOM KANALU","hu":"HANG IDŐ","id":"WAKTU SUARA","it":"TEMPO VOCALE","ja":"ボイス時間","ko":"음성 시간","lt":"BALSO LAIKAS","nl":"SPRAAKTIJD","no":"TALETID","pl":"CZAS GŁOSOWY","pt_BR":"TEMPO DE VOZ","ro":"TIMP VOCAL","ru":"ВРЕМЯ В ГОЛОСОВОМ","sv_SE":"RÖSTTID","th":"เวลาเสียง","tr":"SES SÜRESİ","uk":"ЧАС У ГОЛОСОВОМУ","vi":"THỜI GIAN THOẠI","zh_CN":"语音时间","zh_TW":"語音時間","he_IL":"זמן קולי",
    },
    ("skin:stats|mode:text|subheader:study", "MESSAGES"): {
        "bg":"СЪОБЩЕНИЯ","cs":"ZPRÁVY","da":"BESKEDER","de":"NACHRICHTEN","el":"ΜΗΝΥΜΑΤΑ","es_ES":"MENSAJES","fi":"VIESTIT","fr":"MESSAGES","hi":"संदेश","hr":"PORUKE","hu":"ÜZENETEK","id":"PESAN","it":"MESSAGGI","ja":"メッセージ","ko":"메시지","lt":"ŽINUTĖS","nl":"BERICHTEN","no":"MELDINGER","pl":"WIADOMOŚCI","pt_BR":"MENSAGENS","ro":"MESAJE","ru":"СООБЩЕНИЯ","sv_SE":"MEDDELANDEN","th":"ข้อความ","tr":"MESAJLAR","uk":"ПОВІДОМЛЕННЯ","vi":"TIN NHẮN","zh_CN":"消息","zh_TW":"訊息","he_IL":"הודעות",
    },
    ("skin:stats|mode:anki|subheader:study", "CARDS REVIEWED"): {
        "bg":"ПРЕГЛЕДАНИ КАРТИ","cs":"ZOPAKOVANÉ KARTY","da":"KORT GENNEMGÅET","de":"KARTEN WIEDERHOLT","el":"ΚΑΡΤΕΣ ΠΟΥ ΕΞΕΤΑΣΤΗΚΑΝ","es_ES":"TARJETAS REVISADAS","fi":"KERRATUT KORTIT","fr":"CARTES RÉVISÉES","hi":"समीक्षित कार्ड","hr":"PREGLEDANE KARTICE","hu":"ÁTNÉZETT KÁRTYÁK","id":"KARTU DIULAS","it":"SCHEDE REVISIONATE","ja":"復習したカード","ko":"복습한 카드","lt":"PERŽIŪRĖTOS KORTELĖS","nl":"HERHAALDE KAARTEN","no":"KORT GJENNOMGÅTT","pl":"POWTÓRZONE KARTY","pt_BR":"CARTÕES REVISADOS","ro":"CARDURI REVIZUITE","ru":"ПОВТОРЁННЫЕ КАРТОЧКИ","sv_SE":"KORT REPETERADE","th":"การ์ดที่ทบทวน","tr":"TEKRARLANAN KARTLAR","uk":"ПОВТОРЕНІ КАРТКИ","vi":"THẺ ĐÃ ÔN","zh_CN":"已复习卡片","zh_TW":"已複習卡片","he_IL":"כרטיסים שנבדקו",
    },
    ("skin:stats|subheader:workouts", "WORKOUTS"): {
        "bg":"ТРЕНИРОВКИ","cs":"CVIČENÍ","da":"TRÆNING","de":"WORKOUTS","el":"ΑΣΚΗΣΕΙΣ","es_ES":"ENTRENAMIENTOS","fi":"TREENIT","fr":"ENTRAÎNEMENTS","hi":"वर्कआउट","hr":"VJEŽBE","hu":"EDZÉSEK","id":"LATIHAN","it":"ALLENAMENTI","ja":"ワークアウト","ko":"운동","lt":"TRENIRUOTĖS","nl":"TRAININGEN","no":"TRENINGSØKTER","pl":"ĆWICZENIA","pt_BR":"EXERCÍCIOS","ro":"ANTRENAMENTE","ru":"ТРЕНИРОВКИ","sv_SE":"TRÄNINGSPASS","th":"การออกกำลังกาย","tr":"EGZERSIZLER","uk":"ТРЕНУВАННЯ","vi":"TẬP LUYỆN","zh_CN":"锻炼","zh_TW":"鍛鍊","he_IL":"אימונים",
    },
    ("skin:stats|field:daily", "DAILY"): {"bg":"ДНЕВНО","cs":"DENNĚ","da":"DAGLIG","de":"TÄGLICH","el":"ΗΜΕΡΗΣΙΑ","es_ES":"DIARIO","fi":"PÄIVITTÄIN","fr":"QUOTIDIEN","hi":"दैनिक","hr":"DNEVNO","hu":"NAPONTA","id":"HARIAN","it":"GIORNALIERO","ja":"日間","ko":"일간","lt":"KASDIEN","nl":"DAGELIJKS","no":"DAGLIG","pl":"DZIENNIE","pt_BR":"DIÁRIO","ro":"ZILNIC","ru":"ЗА ДЕНЬ","sv_SE":"DAGLIGEN","th":"รายวัน","tr":"GÜNLÜK","uk":"ЗА ДЕНЬ","vi":"HÀNG NGÀY","zh_CN":"每日","zh_TW":"每日","he_IL":"יומי"},
    ("skin:stats|field:weekly", "WEEKLY"): {"bg":"СЕДМИЧНО","cs":"TÝDNĚ","da":"UGENTLIG","de":"WÖCHENTLICH","el":"ΕΒΔΟΜΑΔΙΑΙΑ","es_ES":"SEMANAL","fi":"VIIKOITTAIN","fr":"HEBDOMADAIRE","hi":"साप्ताहिक","hr":"TJEDNO","hu":"HETENTE","id":"MINGGUAN","it":"SETTIMANALE","ja":"週間","ko":"주간","lt":"SAVAITINIS","nl":"WEKELIJKS","no":"UKENTLIG","pl":"TYGODNIOWO","pt_BR":"SEMANAL","ro":"SĂPTĂMÂNAL","ru":"ЗА НЕДЕЛЮ","sv_SE":"VECKOVIS","th":"รายสัปดาห์","tr":"HAFTALIK","uk":"ЗА ТИЖДЕНЬ","vi":"HÀNG TUẦN","zh_CN":"每周","zh_TW":"每週","he_IL":"שבועי"},
    ("skin:stats|field:monthly", "MONTHLY"): {"bg":"МЕСЕЧНО","cs":"MĚSÍČNĚ","da":"MÅNEDLIG","de":"MONATLICH","el":"ΜΗΝΙΑΙΑ","es_ES":"MENSUAL","fi":"KUUKAUSITTAIN","fr":"MENSUEL","hi":"मासिक","hr":"MJESEČNO","hu":"HAVONTA","id":"BULANAN","it":"MENSILE","ja":"月間","ko":"월간","lt":"MĖNESINIS","nl":"MAANDELIJKS","no":"MÅNEDLIG","pl":"MIESIĘCZNIE","pt_BR":"MENSAL","ro":"LUNAR","ru":"ЗА МЕСЯЦ","sv_SE":"MÅNADSVIS","th":"รายเดือน","tr":"AYLIK","uk":"ЗА МІСЯЦЬ","vi":"HÀNG THÁNG","zh_CN":"每月","zh_TW":"每月","he_IL":"חודשי"},
    ("skin:stats|field:alltime", "ALL TIME"): {"bg":"ОБЩО","cs":"CELKOVĚ","da":"ALLE TIDER","de":"GESAMT","el":"ΣΥΝΟΛΙΚΑ","es_ES":"TOTAL","fi":"KAIKKI AJAT","fr":"TOUT TEMPS","hi":"सर्वकालिक","hr":"UKUPNO","hu":"ÖSSZESEN","id":"SEPANJANG WAKTU","it":"TOTALE","ja":"全期間","ko":"전체","lt":"VISO","nl":"TOTAAL","no":"TOTALT","pl":"ŁĄCZNIE","pt_BR":"TOTAL","ro":"TOTAL","ru":"ЗА ВСЁ ВРЕМЯ","sv_SE":"TOTALT","th":"ทั้งหมด","tr":"TOPLAM","uk":"ЗА ВЕСЬ ЧАС","vi":"TẤT CẢ","zh_CN":"总计","zh_TW":"總計","he_IL":"הכל"},
    ("skin:stats|field:time", "TIME"): {"bg":"ВРЕМЕ","cs":"ČAS","da":"TID","de":"ZEIT","el":"ΧΡΟΝΟΣ","es_ES":"TIEMPO","fi":"AIKA","fr":"TEMPS","hi":"समय","hr":"VRIJEME","hu":"IDŐ","id":"WAKTU","it":"TEMPO","ja":"時間","ko":"시간","lt":"LAIKAS","nl":"TIJD","no":"TID","pl":"CZAS","pt_BR":"TEMPO","ro":"TIMP","ru":"ВРЕМЯ","sv_SE":"TID","th":"เวลา","tr":"SÜRE","uk":"ЧАС","vi":"THỜI GIAN","zh_CN":"时间","zh_TW":"時間","he_IL":"זמן"},
    ("skin:stats|field:anki", "ANKI: COMING SOON"): {"bg":"ANKI: ОЧАКВАЙТЕ СКОРО","cs":"ANKI: BRZY","da":"ANKI: KOMMER SNART","de":"ANKI: DEMNÄCHST","el":"ANKI: ΕΡΧΕΤΑΙ ΣΥΝΤΟΜΑ","es_ES":"ANKI: PRÓXIMAMENTE","fi":"ANKI: TULOSSA PIAN","fr":"ANKI: BIENTÔT","hi":"ANKI: जल्द आ रहा है","hr":"ANKI: USKORO","hu":"ANKI: HAMAROSAN","id":"ANKI: SEGERA HADIR","it":"ANKI: IN ARRIVO","ja":"ANKI: 近日公開","ko":"ANKI: 곧 출시","lt":"ANKI: NETRUKUS","nl":"ANKI: BINNENKORT","no":"ANKI: KOMMER SNART","pl":"ANKI: WKRÓTCE","pt_BR":"ANKI: EM BREVE","ro":"ANKI: ÎN CURÂND","ru":"ANKI: СКОРО","sv_SE":"ANKI: KOMMER SNART","th":"ANKI: เร็วๆ นี้","tr":"ANKI: YAKINDA","uk":"ANKI: НЕЗАБАРОМ","vi":"ANKI: SẮP RA MẮT","zh_CN":"ANKI: 即将推出","zh_TW":"ANKI: 即將推出","he_IL":"Anki: בקרוב"},
    ("skin:stats|mode:study|header:col2", "STUDY STREAK"): {"bg":"ПОРЕДИЦА ОТ УЧЕБНИ ДНИ","cs":"STUDIJNÍ SÉRIE","da":"STUDIESTREAK","de":"LERNSERIE","el":"ΣΕΡΙ ΜΕΛΕΤΗΣ","es_ES":"RACHA DE ESTUDIO","fi":"OPISKELUPUTKI","fr":"SÉRIE D'ÉTUDE","hi":"अध्ययन श्रृंखला","hr":"NIZ UČENJA","hu":"TANULÁSI SOROZAT","id":"STREAK BELAJAR","it":"SERIE DI STUDIO","ja":"学習連続記録","ko":"학습 연속 기록","lt":"MOKYMOSI SERIJA","nl":"STUDIESTREAK","no":"STUDIESTREAK","pl":"SERIA NAUKI","pt_BR":"SEQUÊNCIA DE ESTUDO","ro":"SERIE DE STUDIU","ru":"СЕРИЯ УЧЁБЫ","sv_SE":"STUDIESTREAK","th":"สถิติเรียนต่อเนื่อง","tr":"ÇALIŞMA SERİSİ","uk":"СЕРІЯ НАВЧАННЯ","vi":"CHUỖI HỌC","zh_CN":"学习连续记录","zh_TW":"學習連續記錄","he_IL":"רצף לימודים"},
    ("skin:stats|mode:voice|header:col2", "VOICE STREAK"): {"bg":"ПОРЕДИЦА ОТ ГЛАСОВИ ДНИ","cs":"HLASOVÁ SÉRIE","da":"TALESTREAK","de":"SPRACHSERIE","el":"ΣΕΡΙ ΦΩΝΗΣ","es_ES":"RACHA DE VOZ","fi":"ÄÄNIPUTKI","fr":"SÉRIE VOCALE","hi":"वॉइस श्रृंखला","hr":"NIZ GLASOVNE AKTIVNOSTI","hu":"HANG SOROZAT","id":"STREAK SUARA","it":"SERIE VOCALE","ja":"ボイス連続記録","ko":"음성 연속 기록","lt":"BALSO SERIJA","nl":"SPRAAKSTREAK","no":"TALESTREAK","pl":"SERIA GŁOSOWA","pt_BR":"SEQUÊNCIA DE VOZ","ro":"SERIE VOCALĂ","ru":"СЕРИЯ ГОЛОСОВОЙ","sv_SE":"RÖSTSTREAK","th":"สถิติเสียงต่อเนื่อง","tr":"SES SERİSİ","uk":"СЕРІЯ ГОЛОСОВОГО","vi":"CHUỖI THOẠI","zh_CN":"语音连续记录","zh_TW":"語音連續記錄","he_IL":"רצף קולי"},
    ("skin:stats|mode:text|header:col2", "ACTIVITY STREAK"): {"bg":"ПОРЕДИЦА ОТ АКТИВНИ ДНИ","cs":"SÉRIE AKTIVITY","da":"AKTIVITETSSTREAK","de":"AKTIVITÄTSSERIE","el":"ΣΕΡΙ ΔΡΑΣΤΗΡΙΟΤΗΤΑΣ","es_ES":"RACHA DE ACTIVIDAD","fi":"AKTIIVISUUSPUTKI","fr":"SÉRIE D'ACTIVITÉ","hi":"गतिविधि श्रृंखला","hr":"NIZ AKTIVNOSTI","hu":"AKTIVITÁSI SOROZAT","id":"STREAK AKTIVITAS","it":"SERIE DI ATTIVITÀ","ja":"活動連続記録","ko":"활동 연속 기록","lt":"VEIKLOS SERIJA","nl":"ACTIVITEITSTREAK","no":"AKTIVITETSSTREAK","pl":"SERIA AKTYWNOŚCI","pt_BR":"SEQUÊNCIA DE ATIVIDADE","ro":"SERIE DE ACTIVITATE","ru":"СЕРИЯ АКТИВНОСТИ","sv_SE":"AKTIVITETSSTREAK","th":"สถิติกิจกรรมต่อเนื่อง","tr":"AKTİVİTE SERİSİ","uk":"СЕРІЯ АКТИВНОСТІ","vi":"CHUỖI HOẠT ĐỘNG","zh_CN":"活动连续记录","zh_TW":"活動連續記錄","he_IL":"רצף פעילות"},
    ("skin:stats|mode:anki|header:col2", "ANKI REVIEW STREAK"): {"bg":"ПОРЕДИЦА ОТ ANKI РЕВЮТА","cs":"SÉRIE ANKI OPAKOVÁNÍ","da":"ANKI GENNEMGANGSSTREAK","de":"ANKI-WIEDERHOLUNGSSERIE","el":"ΣΕΡΙ ΑΝΑΘΕΩΡΗΣΕΩΝ ANKI","es_ES":"RACHA DE REPASO ANKI","fi":"ANKI-KERTAUSPUTKI","fr":"SÉRIE DE RÉVISION ANKI","hi":"ANKI रिव्यू श्रृंखला","hr":"NIZ ANKI PREGLEDA","hu":"ANKI ISMÉTLÉS SOROZAT","id":"STREAK ULASAN ANKI","it":"SERIE REVISIONI ANKI","ja":"Anki復習連続記録","ko":"Anki 복습 연속 기록","lt":"ANKI PERŽIŪRŲ SERIJA","nl":"ANKI HERHALINGSSTREAK","no":"ANKI GJENNOMGANGSSTREAK","pl":"SERIA POWTÓREK ANKI","pt_BR":"SEQUÊNCIA DE REVISÃO ANKI","ro":"SERIE REVIZUIRI ANKI","ru":"СЕРИЯ ПОВТОРЕНИЙ ANKI","sv_SE":"ANKI REPETITIONSSTREAK","th":"สถิติทบทวน Anki ต่อเนื่อง","tr":"ANKI TEKRAR SERİSİ","uk":"СЕРІЯ ПОВТОРЕНЬ ANKI","vi":"CHUỖI ÔN TẬP ANKI","zh_CN":"Anki复习连续记录","zh_TW":"Anki複習連續記錄","he_IL":"רצף חזרות Anki"},
    ("skin:stats|mode:study|field:col2_summary", "{amount} HRS"): {l: "{amount} " + {"bg":"ЧАСА","cs":"HOD","da":"TMR","de":"STD","el":"ΩΡΕΣ","es_ES":"HRS","fi":"H","fr":"H","hi":"घंटे","hr":"SATI","hu":"ÓRA","id":"JAM","it":"ORE","ja":"時間","ko":"시간","lt":"VAL","nl":"UUR","no":"TMR","pl":"GODZ","pt_BR":"HRS","ro":"ORE","ru":"Ч","sv_SE":"TIM","th":"ชม.","tr":"SA","uk":"ГОД","vi":"GIỜ","zh_CN":"小时","zh_TW":"小時","he_IL":"שעות"}[l] for l in L},
    ("skin:stats|mode:voice|field:col2_summary", "{amount} HRS"): {l: "{amount} " + {"bg":"ЧАСА","cs":"HOD","da":"TMR","de":"STD","el":"ΩΡΕΣ","es_ES":"HRS","fi":"H","fr":"H","hi":"घंटे","hr":"SATI","hu":"ÓRA","id":"JAM","it":"ORE","ja":"時間","ko":"시간","lt":"VAL","nl":"UUR","no":"TMR","pl":"GODZ","pt_BR":"HRS","ro":"ORE","ru":"Ч","sv_SE":"TIM","th":"ชม.","tr":"SA","uk":"ГОД","vi":"GIỜ","zh_CN":"小时","zh_TW":"小時","he_IL":"שעות"}[l] for l in L},
    ("skin:stats|mode:text|field:col2_summary", "{amount} XP"): {l: "{amount} XP" for l in L},
    ("skin:stats|mode:anki|field:col2_summary", "{amount} CARDS"): {
        "bg":"{amount} КАРТИ","cs":"{amount} KARET","da":"{amount} KORT","de":"{amount} KARTEN","el":"{amount} ΚΑΡΤΕΣ","es_ES":"{amount} TARJETAS","fi":"{amount} KORTTIA","fr":"{amount} CARTES","hi":"{amount} कार्ड","hr":"{amount} KARTICA","hu":"{amount} KÁRTYA","id":"{amount} KARTU","it":"{amount} SCHEDE","ja":"{amount}枚","ko":"{amount}장","lt":"{amount} KORTELIŲ","nl":"{amount} KAARTEN","no":"{amount} KORT","pl":"{amount} KART","pt_BR":"{amount} CARTÕES","ro":"{amount} CARDURI","ru":"{amount} КАРТОЧЕК","sv_SE":"{amount} KORT","th":"{amount} การ์ด","tr":"{amount} KART","uk":"{amount} КАРТОК","vi":"{amount} THẺ","zh_CN":"{amount}张卡片","zh_TW":"{amount}張卡片","he_IL":"{amount} כרטיסים",
    },
    ("skin:stats|cal|weekdays", "S,M,T,W,T,F,S"): WD_SUN,
    ("skin:stats|cal|months", "JANUARY,FEBRUARY,MARCH,APRIL,MAY,JUNE,JULY,AUGUST,SEPTEMBER,OCTOBER,NOVEMBER,DECEMBER"): MONTHS,
}

# Monthly-gui -- similar structure to weekly-gui but with month summaries
MONTHLY_GUI = {
    ("skin:monthlystats|mode:study|title", "STUDY HOURS"): STATS_GUI[("skin:stats|mode:study|subheader:study", "STUDY TIME")].copy(),
    ("skin:monthlystats|mode:voice|title", "VOICE CHANNEL ACTIVITY"): {
        "bg":"АКТИВНОСТ В ГЛАСОВ КАНАЛ","cs":"AKTIVITA HLASOVÉHO KANÁLU","da":"STEMMEKANAL AKTIVITET","de":"SPRACHKANAL-AKTIVITÄT","el":"ΔΡΑΣΤΗΡΙΟΤΗΤΑ ΦΩΝΗΤΙΚΟΥ ΚΑΝΑΛΙΟΥ","es_ES":"ACTIVIDAD DE CANAL DE VOZ","fi":"ÄÄNIKANAVAN AKTIIVISUUS","fr":"ACTIVITÉ DU CANAL VOCAL","hi":"वॉइस चैनल गतिविधि","hr":"AKTIVNOST GLASOVNOG KANALA","hu":"HANGCSATORNA AKTIVITÁS","id":"AKTIVITAS SALURAN SUARA","it":"ATTIVITÀ CANALE VOCALE","ja":"ボイスチャンネル活動","ko":"음성 채널 활동","lt":"BALSO KANALO VEIKLA","nl":"SPRAAKKANAAL ACTIVITEIT","no":"TALEKANAL AKTIVITET","pl":"AKTYWNOŚĆ KANAŁU GŁOSOWEGO","pt_BR":"ATIVIDADE DO CANAL DE VOZ","ro":"ACTIVITATE CANAL VOCAL","ru":"АКТИВНОСТЬ ГОЛОСОВОГО КАНАЛА","sv_SE":"RÖSTKANAL AKTIVITET","th":"กิจกรรมช่องเสียง","tr":"SES KANALI AKTİVİTESİ","uk":"АКТИВНІСТЬ ГОЛОСОВОГО КАНАЛУ","vi":"HOẠT ĐỘNG KÊNH THOẠI","zh_CN":"语音频道活动","zh_TW":"語音頻道活動","he_IL":"פעילות ערוץ קולי",
    },
    ("skin:monthlystats|mode:text|title", "MESSAGE ACTIVITY"): {
        "bg":"АКТИВНОСТ В СЪОБЩЕНИЯТА","cs":"AKTIVITA ZPRÁV","da":"BESKEDAKTIVITET","de":"NACHRICHTENAKTIVITÄT","el":"ΔΡΑΣΤΗΡΙΟΤΗΤΑ ΜΗΝΥΜΑΤΩΝ","es_ES":"ACTIVIDAD DE MENSAJES","fi":"VIESTIEN AKTIIVISUUS","fr":"ACTIVITÉ DES MESSAGES","hi":"संदेश गतिविधि","hr":"AKTIVNOST PORUKA","hu":"ÜZENET AKTIVITÁS","id":"AKTIVITAS PESAN","it":"ATTIVITÀ MESSAGGI","ja":"メッセージ活動","ko":"메시지 활동","lt":"ŽINUČIŲ VEIKLA","nl":"BERICHTENACTIVITEIT","no":"MELDINGSAKTIVITET","pl":"AKTYWNOŚĆ WIADOMOŚCI","pt_BR":"ATIVIDADE DE MENSAGENS","ro":"ACTIVITATE MESAJE","ru":"АКТИВНОСТЬ СООБЩЕНИЙ","sv_SE":"MEDDELANDEAKTIVITET","th":"กิจกรรมข้อความ","tr":"MESAJ AKTİVİTESİ","uk":"АКТИВНІСТЬ ПОВІДОМЛЕНЬ","vi":"HOẠT ĐỘNG TIN NHẮN","zh_CN":"消息活动","zh_TW":"訊息活動","he_IL":"פעילות הודעות",
    },
    ("skin::monthlystats|mode:anki|title", "CARDS REVIEWED"): STATS_GUI[("skin:stats|mode:anki|subheader:study", "CARDS REVIEWED")].copy(),
    ("ui:monthlystats|mode:study|bar_value", "{value} H"): {l: "{value} " + {"bg":"Ч","cs":"H","da":"T","de":"St","el":"Ω","es_ES":"H","fi":"T","fr":"H","hi":"घं","hr":"S","hu":"Ó","id":"J","it":"O","ja":"時","ko":"시","lt":"V","nl":"U","no":"T","pl":"G","pt_BR":"H","ro":"O","ru":"Ч","sv_SE":"T","th":"ชม","tr":"S","uk":"Г","vi":"G","zh_CN":"时","zh_TW":"時","he_IL":"ש"}[l] for l in L},
    ("ui:monthlystats|mode:voice|bar_value", "{value} H"): {l: "{value} " + {"bg":"Ч","cs":"H","da":"T","de":"St","el":"Ω","es_ES":"H","fi":"T","fr":"H","hi":"घं","hr":"S","hu":"Ó","id":"J","it":"O","ja":"時","ko":"시","lt":"V","nl":"U","no":"T","pl":"G","pt_BR":"H","ro":"O","ru":"Ч","sv_SE":"T","th":"ชม","tr":"S","uk":"Г","vi":"G","zh_CN":"时","zh_TW":"時","he_IL":"ש"}[l] for l in L},
    ("ui:monthlystats|mode:text|bar_value", "{value} M"): {l: "{value} M" for l in L},
    ("ui:monthlystats|mode:anki|bar_value", "{value} C"): {l: "{value} C" for l in L},
    ("skin:monthlystats|weekdays", "M,T,W,T,F,S,S"): WD_MON,
    ("skin:monthlystats|mode:study|summary:this_month", "THIS MONTH: {amount} HOURS"): {l: {"bg":"ТОЗИ МЕСЕЦ: {amount} ЧАСА","cs":"TENTO MĚSÍC: {amount} HODIN","da":"DENNE MÅNED: {amount} TIMER","de":"DIESEN MONAT: {amount} STUNDEN","el":"ΑΥΤΟΝ ΤΟΝ ΜΗΝΑ: {amount} ΩΡΕΣ","es_ES":"ESTE MES: {amount} HORAS","fi":"TÄSSÄ KUUSSA: {amount} TUNTIA","fr":"CE MOIS : {amount} HEURES","hi":"इस महीने: {amount} घंटे","hr":"OVAJ MJESEC: {amount} SATI","hu":"EBBEN A HÓNAPBAN: {amount} ÓRA","id":"BULAN INI: {amount} JAM","it":"QUESTO MESE: {amount} ORE","ja":"今月: {amount}時間","ko":"이번 달: {amount}시간","lt":"ŠĮ MĖNESĮ: {amount} VAL.","nl":"DEZE MAAND: {amount} UUR","no":"DENNE MÅNEDEN: {amount} TIMER","pl":"TEN MIESIĄC: {amount} GODZIN","pt_BR":"ESTE MÊS: {amount} HORAS","ro":"LUNA ACEASTA: {amount} ORE","ru":"В ЭТОМ МЕСЯЦЕ: {amount} ЧАСОВ","sv_SE":"DENNA MÅNAD: {amount} TIMMAR","th":"เดือนนี้: {amount} ชั่วโมง","tr":"BU AY: {amount} SAAT","uk":"ЦЬОГО МІСЯЦЯ: {amount} ГОДИН","vi":"THÁNG NÀY: {amount} GIỜ","zh_CN":"本月: {amount}小时","zh_TW":"本月: {amount}小時","he_IL":"החודש: {amount} שעות"}[l] for l in L},
    ("skin:monthlystats|mode:voice|summary:this_month", "THIS MONTH: {amount} HOURS"): {l: {"bg":"ТОЗИ МЕСЕЦ: {amount} ЧАСА","cs":"TENTO MĚSÍC: {amount} HODIN","da":"DENNE MÅNED: {amount} TIMER","de":"DIESEN MONAT: {amount} STUNDEN","el":"ΑΥΤΟΝ ΤΟΝ ΜΗΝΑ: {amount} ΩΡΕΣ","es_ES":"ESTE MES: {amount} HORAS","fi":"TÄSSÄ KUUSSA: {amount} TUNTIA","fr":"CE MOIS : {amount} HEURES","hi":"इस महीने: {amount} घंटे","hr":"OVAJ MJESEC: {amount} SATI","hu":"EBBEN A HÓNAPBAN: {amount} ÓRA","id":"BULAN INI: {amount} JAM","it":"QUESTO MESE: {amount} ORE","ja":"今月: {amount}時間","ko":"이번 달: {amount}시간","lt":"ŠĮ MĖNESĮ: {amount} VAL.","nl":"DEZE MAAND: {amount} UUR","no":"DENNE MÅNEDEN: {amount} TIMER","pl":"TEN MIESIĄC: {amount} GODZIN","pt_BR":"ESTE MÊS: {amount} HORAS","ro":"LUNA ACEASTA: {amount} ORE","ru":"В ЭТОМ МЕСЯЦЕ: {amount} ЧАСОВ","sv_SE":"DENNA MÅNAD: {amount} TIMMAR","th":"เดือนนี้: {amount} ชั่วโมง","tr":"BU AY: {amount} SAAT","uk":"ЦЬОГО МІСЯЦЯ: {amount} ГОДИН","vi":"THÁNG NÀY: {amount} GIỜ","zh_CN":"本月: {amount}小时","zh_TW":"本月: {amount}小時","he_IL":"החודש: {amount} שעות"}[l] for l in L},
    ("skin:monthlystats|mode:text|summary:this_month", "THIS MONTH: {amount} MESSAGES"): {l: {"bg":"ТОЗИ МЕСЕЦ: {amount} СЪОБЩЕНИЯ","cs":"TENTO MĚSÍC: {amount} ZPRÁV","da":"DENNE MÅNED: {amount} BESKEDER","de":"DIESEN MONAT: {amount} NACHRICHTEN","el":"ΑΥΤΟΝ ΤΟΝ ΜΗΝΑ: {amount} ΜΗΝΥΜΑΤΑ","es_ES":"ESTE MES: {amount} MENSAJES","fi":"TÄSSÄ KUUSSA: {amount} VIESTIÄ","fr":"CE MOIS : {amount} MESSAGES","hi":"इस महीने: {amount} संदेश","hr":"OVAJ MJESEC: {amount} PORUKA","hu":"EBBEN A HÓNAPBAN: {amount} ÜZENET","id":"BULAN INI: {amount} PESAN","it":"QUESTO MESE: {amount} MESSAGGI","ja":"今月: {amount}メッセージ","ko":"이번 달: {amount}메시지","lt":"ŠĮ MĖNESĮ: {amount} ŽINUČIŲ","nl":"DEZE MAAND: {amount} BERICHTEN","no":"DENNE MÅNEDEN: {amount} MELDINGER","pl":"TEN MIESIĄC: {amount} WIADOMOŚCI","pt_BR":"ESTE MÊS: {amount} MENSAGENS","ro":"LUNA ACEASTA: {amount} MESAJE","ru":"В ЭТОМ МЕСЯЦЕ: {amount} СООБЩЕНИЙ","sv_SE":"DENNA MÅNAD: {amount} MEDDELANDEN","th":"เดือนนี้: {amount} ข้อความ","tr":"BU AY: {amount} MESAJ","uk":"ЦЬОГО МІСЯЦЯ: {amount} ПОВІДОМЛЕНЬ","vi":"THÁNG NÀY: {amount} TIN NHẮN","zh_CN":"本月: {amount}条消息","zh_TW":"本月: {amount}則訊息","he_IL":"החודש: {amount} הודעות"}[l] for l in L},
    ("skin:monthlystats|mode:text|summary:this_month", "THIS MONTH: {amount} CARDS"): {l: {"bg":"ТОЗИ МЕСЕЦ: {amount} КАРТИ","cs":"TENTO MĚSÍC: {amount} KARET","da":"DENNE MÅNED: {amount} KORT","de":"DIESEN MONAT: {amount} KARTEN","el":"ΑΥΤΟΝ ΤΟΝ ΜΗΝΑ: {amount} ΚΑΡΤΕΣ","es_ES":"ESTE MES: {amount} TARJETAS","fi":"TÄSSÄ KUUSSA: {amount} KORTTIA","fr":"CE MOIS : {amount} CARTES","hi":"इस महीने: {amount} कार्ड","hr":"OVAJ MJESEC: {amount} KARTICA","hu":"EBBEN A HÓNAPBAN: {amount} KÁRTYA","id":"BULAN INI: {amount} KARTU","it":"QUESTO MESE: {amount} SCHEDE","ja":"今月: {amount}枚","ko":"이번 달: {amount}장","lt":"ŠĮ MĖNESĮ: {amount} KORTELIŲ","nl":"DEZE MAAND: {amount} KAARTEN","no":"DENNE MÅNEDEN: {amount} KORT","pl":"TEN MIESIĄC: {amount} KART","pt_BR":"ESTE MÊS: {amount} CARTÕES","ro":"LUNA ACEASTA: {amount} CARDURI","ru":"В ЭТОМ МЕСЯЦЕ: {amount} КАРТОЧЕК","sv_SE":"DENNA MÅNAD: {amount} KORT","th":"เดือนนี้: {amount} การ์ด","tr":"BU AY: {amount} KART","uk":"ЦЬОГО МІСЯЦЯ: {amount} КАРТОК","vi":"THÁNG NÀY: {amount} THẺ","zh_CN":"本月: {amount}张卡片","zh_TW":"本月: {amount}張卡片","he_IL":"החודש: {amount} כרטיסים"}[l] for l in L},
    ("skin:monthlystats|mode:study|summary:last_month", "LAST MONTH: {amount} HOURS"): {l: {"bg":"МИНАЛИЯТ МЕСЕЦ: {amount} ЧАСА","cs":"MINULÝ MĚSÍC: {amount} HODIN","da":"SIDSTE MÅNED: {amount} TIMER","de":"LETZTEN MONAT: {amount} STUNDEN","el":"ΠΡΟΗΓΟΥΜΕΝΟΣ ΜΗΝΑΣ: {amount} ΩΡΕΣ","es_ES":"MES PASADO: {amount} HORAS","fi":"VIIME KUUSSA: {amount} TUNTIA","fr":"MOIS DERNIER : {amount} HEURES","hi":"पिछला महीना: {amount} घंटे","hr":"PROŠLI MJESEC: {amount} SATI","hu":"MÚLT HÓNAPBAN: {amount} ÓRA","id":"BULAN LALU: {amount} JAM","it":"MESE SCORSO: {amount} ORE","ja":"先月: {amount}時間","ko":"지난 달: {amount}시간","lt":"PRAĖJUSĮ MĖNESĮ: {amount} VAL.","nl":"VORIGE MAAND: {amount} UUR","no":"FORRIGE MÅNED: {amount} TIMER","pl":"ZESZŁY MIESIĄC: {amount} GODZIN","pt_BR":"MÊS PASSADO: {amount} HORAS","ro":"LUNA TRECUTĂ: {amount} ORE","ru":"В ПРОШЛОМ МЕСЯЦЕ: {amount} ЧАСОВ","sv_SE":"FÖRRA MÅNADEN: {amount} TIMMAR","th":"เดือนก่อน: {amount} ชั่วโมง","tr":"GEÇEN AY: {amount} SAAT","uk":"МИНУЛОГО МІСЯЦЯ: {amount} ГОДИН","vi":"THÁNG TRƯỚC: {amount} GIỜ","zh_CN":"上月: {amount}小时","zh_TW":"上月: {amount}小時","he_IL":"חודש שעבר: {amount} שעות"}[l] for l in L},
    ("skin:monthlystats|mode:voice|summary:last_month", "LAST MONTH: {amount} HOURS"): {l: {"bg":"МИНАЛИЯТ МЕСЕЦ: {amount} ЧАСА","cs":"MINULÝ MĚSÍC: {amount} HODIN","da":"SIDSTE MÅNED: {amount} TIMER","de":"LETZTEN MONAT: {amount} STUNDEN","el":"ΠΡΟΗΓΟΥΜΕΝΟΣ ΜΗΝΑΣ: {amount} ΩΡΕΣ","es_ES":"MES PASADO: {amount} HORAS","fi":"VIIME KUUSSA: {amount} TUNTIA","fr":"MOIS DERNIER : {amount} HEURES","hi":"पिछला महीना: {amount} घंटे","hr":"PROŠLI MJESEC: {amount} SATI","hu":"MÚLT HÓNAPBAN: {amount} ÓRA","id":"BULAN LALU: {amount} JAM","it":"MESE SCORSO: {amount} ORE","ja":"先月: {amount}時間","ko":"지난 달: {amount}시간","lt":"PRAĖJUSĮ MĖNESĮ: {amount} VAL.","nl":"VORIGE MAAND: {amount} UUR","no":"FORRIGE MÅNED: {amount} TIMER","pl":"ZESZŁY MIESIĄC: {amount} GODZIN","pt_BR":"MÊS PASSADO: {amount} HORAS","ro":"LUNA TRECUTĂ: {amount} ORE","ru":"В ПРОШЛОМ МЕСЯЦЕ: {amount} ЧАСОВ","sv_SE":"FÖRRA MÅNADEN: {amount} TIMMAR","th":"เดือนก่อน: {amount} ชั่วโมง","tr":"GEÇEN AY: {amount} SAAT","uk":"МИНУЛОГО МІСЯЦЯ: {amount} ГОДИН","vi":"THÁNG TRƯỚC: {amount} GIỜ","zh_CN":"上月: {amount}小时","zh_TW":"上月: {amount}小時","he_IL":"חודש שעבר: {amount} שעות"}[l] for l in L},
    ("skin:monthlystats|mode:text|summary:last_month", "LAST MONTH: {amount} MESSAGES"): {l: {"bg":"МИНАЛИЯТ МЕСЕЦ: {amount} СЪОБЩЕНИЯ","cs":"MINULÝ MĚSÍC: {amount} ZPRÁV","da":"SIDSTE MÅNED: {amount} BESKEDER","de":"LETZTEN MONAT: {amount} NACHRICHTEN","el":"ΠΡΟΗΓΟΥΜΕΝΟΣ ΜΗΝΑΣ: {amount} ΜΗΝΥΜΑΤΑ","es_ES":"MES PASADO: {amount} MENSAJES","fi":"VIIME KUUSSA: {amount} VIESTIÄ","fr":"MOIS DERNIER : {amount} MESSAGES","hi":"पिछला महीना: {amount} संदेश","hr":"PROŠLI MJESEC: {amount} PORUKA","hu":"MÚLT HÓNAPBAN: {amount} ÜZENET","id":"BULAN LALU: {amount} PESAN","it":"MESE SCORSO: {amount} MESSAGGI","ja":"先月: {amount}メッセージ","ko":"지난 달: {amount}메시지","lt":"PRAĖJUSĮ MĖNESĮ: {amount} ŽINUČIŲ","nl":"VORIGE MAAND: {amount} BERICHTEN","no":"FORRIGE MÅNED: {amount} MELDINGER","pl":"ZESZŁY MIESIĄC: {amount} WIADOMOŚCI","pt_BR":"MÊS PASSADO: {amount} MENSAGENS","ro":"LUNA TRECUTĂ: {amount} MESAJE","ru":"В ПРОШЛОМ МЕСЯЦЕ: {amount} СООБЩЕНИЙ","sv_SE":"FÖRRA MÅNADEN: {amount} MEDDELANDEN","th":"เดือนก่อน: {amount} ข้อความ","tr":"GEÇEN AY: {amount} MESAJ","uk":"МИНУЛОГО МІСЯЦЯ: {amount} ПОВІДОМЛЕНЬ","vi":"THÁNG TRƯỚC: {amount} TIN NHẮN","zh_CN":"上月: {amount}条消息","zh_TW":"上月: {amount}則訊息","he_IL":"חודש שעבר: {amount} הודעות"}[l] for l in L},
    ("skin:monthlystats|mode:text|summary:last_month", "LAST MONTH: {amount} CARDS"): {l: {"bg":"МИНАЛИЯТ МЕСЕЦ: {amount} КАРТИ","cs":"MINULÝ MĚSÍC: {amount} KARET","da":"SIDSTE MÅNED: {amount} KORT","de":"LETZTEN MONAT: {amount} KARTEN","el":"ΠΡΟΗΓΟΥΜΕΝΟΣ ΜΗΝΑΣ: {amount} ΚΑΡΤΕΣ","es_ES":"MES PASADO: {amount} TARJETAS","fi":"VIIME KUUSSA: {amount} KORTTIA","fr":"MOIS DERNIER : {amount} CARTES","hi":"पिछला महीना: {amount} कार्ड","hr":"PROŠLI MJESEC: {amount} KARTICA","hu":"MÚLT HÓNAPBAN: {amount} KÁRTYA","id":"BULAN LALU: {amount} KARTU","it":"MESE SCORSO: {amount} SCHEDE","ja":"先月: {amount}枚","ko":"지난 달: {amount}장","lt":"PRAĖJUSĮ MĖNESĮ: {amount} KORTELIŲ","nl":"VORIGE MAAND: {amount} KAARTEN","no":"FORRIGE MÅNED: {amount} KORT","pl":"ZESZŁY MIESIĄC: {amount} KART","pt_BR":"MÊS PASSADO: {amount} CARTÕES","ro":"LUNA TRECUTĂ: {amount} CARDURI","ru":"В ПРОШЛОМ МЕСЯЦЕ: {amount} КАРТОЧЕК","sv_SE":"FÖRRA MÅNADEN: {amount} KORT","th":"เดือนก่อน: {amount} การ์ด","tr":"GEÇEN AY: {amount} KART","uk":"МИНУЛОГО МІСЯЦЯ: {amount} КАРТОК","vi":"THÁNG TRƯỚC: {amount} THẺ","zh_CN":"上月: {amount}张卡片","zh_TW":"上月: {amount}張卡片","he_IL":"חודש שעבר: {amount} כרטיסים"}[l] for l in L},
    ("ui:monthlystats|stats:current_streak|key", "Current Streak:"): {"bg":"Текуща поредица:","cs":"Aktuální série:","da":"Aktuel streak:","de":"Aktuelle Serie:","el":"Τρέχον σερί:","es_ES":"Racha actual:","fi":"Nykyinen putki:","fr":"Série actuelle :","hi":"वर्तमान श्रृंखला:","hr":"Trenutni niz:","hu":"Jelenlegi sorozat:","id":"Streak saat ini:","it":"Serie attuale:","ja":"現在の連続記録:","ko":"현재 연속 기록:","lt":"Dabartinė serija:","nl":"Huidige streak:","no":"Nåværende streak:","pl":"Obecna seria:","pt_BR":"Sequência atual:","ro":"Serie curentă:","ru":"Текущая серия:","sv_SE":"Nuvarande streak:","th":"สถิติต่อเนื่องปัจจุบัน:","tr":"Mevcut seri:","uk":"Поточна серія:","vi":"Chuỗi hiện tại:","zh_CN":"当前连续记录:","zh_TW":"當前連續記錄:","he_IL":"רצף נוכחי:"},
    ("ui:monthlystats|stats:current_streak|value", "{count} days"): {"bg":"{count} дни","cs":"{count} dní","da":"{count} dage","de":"{count} Tage","el":"{count} ημέρες","es_ES":"{count} días","fi":"{count} päivää","fr":"{count} jours","hi":"{count} दिन","hr":"{count} dana","hu":"{count} nap","id":"{count} hari","it":"{count} giorni","ja":"{count}日","ko":"{count}일","lt":"{count} d.","nl":"{count} dagen","no":"{count} dager","pl":"{count} dni","pt_BR":"{count} dias","ro":"{count} zile","ru":"{count} дней","sv_SE":"{count} dagar","th":"{count} วัน","tr":"{count} gün","uk":"{count} днів","vi":"{count} ngày","zh_CN":"{count}天","zh_TW":"{count}天","he_IL":"{count} ימים"},
    ("ui:monthlystats|stats:longest_streak|key", "Longest Streak:"): {"bg":"Най-дълга поредица:","cs":"Nejdelší série:","da":"Længste streak:","de":"Längste Serie:","el":"Μεγαλύτερο σερί:","es_ES":"Racha más larga:","fi":"Pisin putki:","fr":"Plus longue série :","hi":"सबसे लंबी श्रृंखला:","hr":"Najduži niz:","hu":"Leghosszabb sorozat:","id":"Streak terpanjang:","it":"Serie più lunga:","ja":"最長連続記録:","ko":"최장 연속 기록:","lt":"Ilgiausia serija:","nl":"Langste streak:","no":"Lengste streak:","pl":"Najdłuższa seria:","pt_BR":"Maior sequência:","ro":"Cea mai lungă serie:","ru":"Самая длинная серия:","sv_SE":"Längsta streak:","th":"สถิติต่อเนื่องยาวที่สุด:","tr":"En uzun seri:","uk":"Найдовша серія:","vi":"Chuỗi dài nhất:","zh_CN":"最长连续记录:","zh_TW":"最長連續記錄:","he_IL":"רצף ארוך ביותר:"},
    ("ui:monthlystats|stats:longest_streak|value", "{count} days"): {"bg":"{count} дни","cs":"{count} dní","da":"{count} dage","de":"{count} Tage","el":"{count} ημέρες","es_ES":"{count} días","fi":"{count} päivää","fr":"{count} jours","hi":"{count} दिन","hr":"{count} dana","hu":"{count} nap","id":"{count} hari","it":"{count} giorni","ja":"{count}日","ko":"{count}일","lt":"{count} d.","nl":"{count} dagen","no":"{count} dager","pl":"{count} dni","pt_BR":"{count} dias","ro":"{count} zile","ru":"{count} дней","sv_SE":"{count} dagar","th":"{count} วัน","tr":"{count} gün","uk":"{count} днів","vi":"{count} ngày","zh_CN":"{count}天","zh_TW":"{count}天","he_IL":"{count} ימים"},
    ("ui:monthlystats|stats:daily_average|key", "Daily Average:"): {"bg":"Средно на ден:","cs":"Denní průměr:","da":"Dagligt gennemsnit:","de":"Tagesdurchschnitt:","el":"Ημερήσιος μέσος:","es_ES":"Promedio diario:","fi":"Päivittäinen keskiarvo:","fr":"Moyenne quotidienne :","hi":"दैनिक औसत:","hr":"Dnevni prosjek:","hu":"Napi átlag:","id":"Rata-rata harian:","it":"Media giornaliera:","ja":"日平均:","ko":"일일 평균:","lt":"Dienos vidurkis:","nl":"Dagelijks gemiddelde:","no":"Daglig gjennomsnitt:","pl":"Średnia dzienna:","pt_BR":"Média diária:","ro":"Media zilnică:","ru":"Среднее за день:","sv_SE":"Dagligt genomsnitt:","th":"ค่าเฉลี่ยรายวัน:","tr":"Günlük ortalama:","uk":"Середнє за день:","vi":"Trung bình hàng ngày:","zh_CN":"日均:","zh_TW":"日均:","he_IL":"ממוצע יומי:"},
    ("skin:monthlystats|mode:study|stats:daily_average|value", "{count} hours"): {l: "{count} " + H[l] for l in L},
    ("skin:monthlystats|mode:voice|stats:daily_average|value", "{count} hours"): {l: "{count} " + H[l] for l in L},
    ("skin:monthlystats|mode:text|stats:daily_average|value", "{count} msgs"): {"bg":"{count} съобщ.","cs":"{count} zpr.","da":"{count} besk.","de":"{count} Nachr.","el":"{count} μνμ.","es_ES":"{count} msjs","fi":"{count} viest.","fr":"{count} msgs","hi":"{count} संदेश","hr":"{count} por.","hu":"{count} üz.","id":"{count} psn","it":"{count} msg","ja":"{count}件","ko":"{count}개","lt":"{count} žin.","nl":"{count} ber.","no":"{count} meld.","pl":"{count} wiad.","pt_BR":"{count} msgs","ro":"{count} msj","ru":"{count} сообщ.","sv_SE":"{count} medd.","th":"{count} ข้อความ","tr":"{count} msj","uk":"{count} повід.","vi":"{count} tin","zh_CN":"{count}条","zh_TW":"{count}則","he_IL":"{count} הודעות"},
    ("skin:monthlystats|mode:anki|stats:daily_average|value", "{count} cards"): {"bg":"{count} карти","cs":"{count} karet","da":"{count} kort","de":"{count} Karten","el":"{count} κάρτες","es_ES":"{count} tarjetas","fi":"{count} korttia","fr":"{count} cartes","hi":"{count} कार्ड","hr":"{count} kartica","hu":"{count} kártya","id":"{count} kartu","it":"{count} schede","ja":"{count}枚","ko":"{count}장","lt":"{count} kortelių","nl":"{count} kaarten","no":"{count} kort","pl":"{count} kart","pt_BR":"{count} cartões","ro":"{count} carduri","ru":"{count} карточек","sv_SE":"{count} kort","th":"{count} การ์ด","tr":"{count} kart","uk":"{count} карток","vi":"{count} thẻ","zh_CN":"{count}张","zh_TW":"{count}張","he_IL":"{count} כרטיסים"},
    ("ui:monthlystats|stats:days_active|key", "Days Active:"): {"bg":"Активни дни:","cs":"Aktivní dny:","da":"Aktive dage:","de":"Aktive Tage:","el":"Ενεργές ημέρες:","es_ES":"Días activos:","fi":"Aktiiviset päivät:","fr":"Jours actifs :","hi":"सक्रिय दिन:","hr":"Aktivni dani:","hu":"Aktív napok:","id":"Hari aktif:","it":"Giorni attivi:","ja":"アクティブ日数:","ko":"활동일:","lt":"Aktyvios dienos:","nl":"Actieve dagen:","no":"Aktive dager:","pl":"Aktywne dni:","pt_BR":"Dias ativos:","ro":"Zile active:","ru":"Активных дней:","sv_SE":"Aktiva dagar:","th":"วันที่ใช้งาน:","tr":"Aktif günler:","uk":"Активних днів:","vi":"Ngày hoạt động:","zh_CN":"活跃天数:","zh_TW":"活躍天數:","he_IL":"ימים פעילים:"},
    ("ui:monthlystats|stats:days_active|value", "{count} days"): {"bg":"{count} дни","cs":"{count} dní","da":"{count} dage","de":"{count} Tage","el":"{count} ημέρες","es_ES":"{count} días","fi":"{count} päivää","fr":"{count} jours","hi":"{count} दिन","hr":"{count} dana","hu":"{count} nap","id":"{count} hari","it":"{count} giorni","ja":"{count}日","ko":"{count}일","lt":"{count} d.","nl":"{count} dagen","no":"{count} dager","pl":"{count} dni","pt_BR":"{count} dias","ro":"{count} zile","ru":"{count} дней","sv_SE":"{count} dagar","th":"{count} วัน","tr":"{count} gün","uk":"{count} днів","vi":"{count} ngày","zh_CN":"{count}天","zh_TW":"{count}天","he_IL":"{count} ימים"},
    ("skin:monthlystats|footer", "Monthly Statistics \u2022 As of {day} {month} \u2022 {name} {discrim}"): {"bg":"Месечна статистика \u2022 Към {day} {month} \u2022 {name} {discrim}","cs":"Měsíční statistiky \u2022 K {day} {month} \u2022 {name} {discrim}","da":"Månedlig statistik \u2022 Pr. {day} {month} \u2022 {name} {discrim}","de":"Monatsstatistik \u2022 Stand {day} {month} \u2022 {name} {discrim}","el":"Μηνιαία στατιστικά \u2022 Από {day} {month} \u2022 {name} {discrim}","es_ES":"Estadísticas mensuales \u2022 Al {day} {month} \u2022 {name} {discrim}","fi":"Kuukausitilastot \u2022 {day} {month} mennessä \u2022 {name} {discrim}","fr":"Statistiques mensuelles \u2022 Au {day} {month} \u2022 {name} {discrim}","hi":"मासिक आँकड़े \u2022 {day} {month} तक \u2022 {name} {discrim}","hr":"Mjesečna statistika \u2022 Na dan {day} {month} \u2022 {name} {discrim}","hu":"Havi statisztikák \u2022 {day} {month} állapot \u2022 {name} {discrim}","id":"Statistik Bulanan \u2022 Per {day} {month} \u2022 {name} {discrim}","it":"Statistiche mensili \u2022 Al {day} {month} \u2022 {name} {discrim}","ja":"月間統計 \u2022 {day} {month}時点 \u2022 {name} {discrim}","ko":"월간 통계 \u2022 {day} {month} 기준 \u2022 {name} {discrim}","lt":"Mėnesio statistika \u2022 {day} {month} \u2022 {name} {discrim}","nl":"Maandelijkse statistieken \u2022 Per {day} {month} \u2022 {name} {discrim}","no":"Månedlig statistikk \u2022 Per {day} {month} \u2022 {name} {discrim}","pl":"Statystyki miesięczne \u2022 Na dzień {day} {month} \u2022 {name} {discrim}","pt_BR":"Estatísticas mensais \u2022 Em {day} {month} \u2022 {name} {discrim}","ro":"Statistici lunare \u2022 La {day} {month} \u2022 {name} {discrim}","ru":"Месячная статистика \u2022 На {day} {month} \u2022 {name} {discrim}","sv_SE":"Månadsstatistik \u2022 Per {day} {month} \u2022 {name} {discrim}","th":"สถิติรายเดือน \u2022 ณ {day} {month} \u2022 {name} {discrim}","tr":"Aylık İstatistikler \u2022 {day} {month} itibarıyla \u2022 {name} {discrim}","uk":"Місячна статистика \u2022 Станом на {day} {month} \u2022 {name} {discrim}","vi":"Thống kê hàng tháng \u2022 Tính đến {day} {month} \u2022 {name} {discrim}","zh_CN":"每月统计 \u2022 截至{day} {month} \u2022 {name} {discrim}","zh_TW":"每月統計 \u2022 截至{day} {month} \u2022 {name} {discrim}","he_IL":"סטטיסטיקה חודשית \u2022 נכון ל-{day} {month} \u2022 {name} {discrim}"},
}

# Fix monthly STUDY HOURS title
MONTHLY_GUI[("skin:monthlystats|mode:study|title", "STUDY HOURS")] = {
    "bg":"УЧЕБНИ ЧАСОВЕ","cs":"HODINY STUDIA","da":"STUDIETIMER","de":"LERNSTUNDEN","el":"ΩΡΕΣ ΜΕΛΕΤΗΣ","es_ES":"HORAS DE ESTUDIO","fi":"OPISKELUTUNNIT","fr":"HEURES D'ÉTUDE","hi":"अध्ययन के घंटे","hr":"SATI UČENJA","hu":"TANULÁSI ÓRÁK","id":"JAM BELAJAR","it":"ORE DI STUDIO","ja":"学習時間","ko":"학습 시간","lt":"MOKYMOSI VALANDOS","nl":"STUDIE-UREN","no":"STUDIETIMER","pl":"GODZINY NAUKI","pt_BR":"HORAS DE ESTUDO","ro":"ORE DE STUDIU","ru":"ЧАСЫ УЧЁБЫ","sv_SE":"STUDIETIMMAR","th":"ชั่วโมงเรียน","tr":"ÇALIŞMA SAATLERİ","uk":"ГОДИНИ НАВЧАННЯ","vi":"GIỜ HỌC","zh_CN":"学习时间","zh_TW":"學習時間","he_IL":"שעות לימוד",
}


def run_domain(domain, ai_translations):
    pot_path = os.path.join(TEMPLATES_DIR, f"{domain}.pot")
    entries = parse_pot(pot_path)
    print(f"  {domain}: {len(entries)} strings")
    salvaged = load_salvaged(domain)
    existing = load_existing_translations(domain)
    merged = {}
    for key, locale_map in salvaged.items():
        merged[key] = locale_map.copy()
    for key, locale_map in ai_translations.items():
        if key not in merged:
            merged[key] = {}
        for locale, text in locale_map.items():
            if locale not in merged[key]:
                merged[key][locale] = text
    count = write_po_files(domain, entries, merged, existing_map=existing)
    print(f"    -> wrote {count} .po files")


def main():
    print("=== Generating medium domain translations ===")
    run_domain("stats-gui", STATS_GUI)
    run_domain("monthly-gui", MONTHLY_GUI)
    print("Done!")


if __name__ == '__main__':
    main()
